/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ApiPublicUpdateWindowsRouteImport } from './routes/api/public/update/windows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUpdateWindowsRoute = ApiPublicUpdateWindowsRouteImport.update({
  id: '/api/public/update/windows',
  path: '/api/public/update/windows',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/setup': typeof SetupRoute
  '/training': typeof TrainingRoute
  '/api/public/update/windows': typeof ApiPublicUpdateWindowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/setup': typeof SetupRoute
  '/training': typeof TrainingRoute
  '/api/public/update/windows': typeof ApiPublicUpdateWindowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/setup': typeof SetupRoute
  '/training': typeof TrainingRoute
  '/api/public/update/windows': typeof ApiPublicUpdateWindowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/download' | '/setup' | '/training' | '/api/public/update/windows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download' | '/setup' | '/training' | '/api/public/update/windows'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/setup'
    | '/training'
    | '/api/public/update/windows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  SetupRoute: typeof SetupRoute
  TrainingRoute: typeof TrainingRoute
  ApiPublicUpdateWindowsRoute: typeof ApiPublicUpdateWindowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/update/windows': {
      id: '/api/public/update/windows'
      path: '/api/public/update/windows'
      fullPath: '/api/public/update/windows'
      preLoaderRoute: typeof ApiPublicUpdateWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  SetupRoute: SetupRoute,
  TrainingRoute: TrainingRoute,
  ApiPublicUpdateWindowsRoute: ApiPublicUpdateWindowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
